#!/bin/bash

# ##############################################################################
# #                                  Monitor
# ##############################################################################

sh $HOME/.screenlayout/HDMI.sh

# ##############################################################################
# #                                  Config
# ##############################################################################

WALLPAPER_PATH="$HOME/Pictures/Wallpapers/wallpaper.png"

# ##############################################################################
# #                                  ENV VARS                                  #
# ##############################################################################

export BROWSER=firefox-nightly
export MONITOR=$(xrandr -q | grep primary | cut -d' ' -f1)
export MONITORS=( $(xrandr -q | grep ' connected' | cut -d' ' -f1 | sort -r) )
export QT_STYLE_OVERRIDE=kvantum

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

# start sxhkd
# sh $HOME/.config/sxhkd/multi_mode_sxhkd.sh start &
# no capslock, switch to ctrl
setxkbmap -option ctrl:nocaps
# turn off bell
xset -b
# start dunst
if pgrep -x dunst > /dev/null
then
    kill $(pidof dunst)
fi
dunst --startup_notification true --config $HOME/.config/dunst/dunstrc &
# start picom, it will autoreload config file, so it don't need to stop
picom --experimental-backends --config $HOME/.config/picom/picom.conf &
# start polybar
sh $HOME/.config/polybar/launch.sh
# start fcitx
fcitx5-remote -r
# auto lock screen
#xautolock -time 10 -locker 'lock' -corners ---- -cornersize 30 &
xautolock -time 10 -locker 'systemctl suspend' -corners ---- -cornersize 30 &
# set wallpaper
hsetroot -cover $WALLPAPER_PATH
# battery checker
sh $HOME/.local/bin/check-battery.sh &
# start conky
sh $HOME/.config/conky/start.sh &
# start redshift
if pgrep -x redshift > /dev/null
then
    pid=$(pidof redshift)
    kill $pid
    # we need to wait redshift shutdown, otherwise color temperature is wrong.
    while kill -0 $pid 2>/dev/null; do sleep 0.01; done
fi
redshift &

# ActivityWatch Family
aw-server &
aw-watcher-afk &
aw-watcher-window &

# clipboard manager
greenclip daemon > /dev/null 2>&1 &

# Force keyborad
# xinput set-prop $(xinput list  | grep Touchpad | grep -Eo "id=[0-9]{1,4}" | cut -d '=' -f 2) "Device Enabled" 0
# xinput set-prop $(xinput list  | grep Mouse | grep -Eo "id=[0-9]{1,4}" | cut -d '=' -f 2) "Device Enabled" 0

if pgrep -x unclutter > /dev/null
then
    pid=$(pidof unclutter)
    kill $pid
    while kill -0 $pid 2>/dev/null; do sleep 0.01; done
fi
unclutter -idle 10 &

# latte-dock &
#bspc rule -a dropdown sticky=on state=floating hidden=on
#alacritty --class dropdown -e "zsh" &

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

bspc rule -a Nightly                        desktop=^1 state=tiled
bspc rule -a code-oss                       desktop=^5 state=fullscreen
bspc rule -a Mailspring                     desktop=^7 state=tiled
bspc rule -a TelegramDesktop                desktop=^7 state=tiled
bspc rule -a Conky                          sticky=on manage=off lower=on
bspc rule -a Xfce4-terminal                 state=floating border=off
bspc rule -a latte-dock                     sticky=on manage=off
# xprop WM_CLASS and WM_NAME
# bspc rule -a 'Toolkit:firefox-nightly:Picture-in-Picture' sticky=on manage=off lower=on
bspc rule -a '*:*:Picture-in-Picture' sticky=on manage=off lower=on

bspc desktop ^7 -l monocle

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

MONITOR=${MONITOR:-${MONITORS[0]}}
bspc monitor $MONITOR -d I II III IV V VI VII

# pointer_modifier
#     Keyboard modifier used for moving or resizing windows. Accept the following values: shift, control, lock, mod1, mod2,
#     mod3, mod4, mod5.
bspc config pointer_modifier             Mod4  # Super(Win)

# window border width
bspc config border_width                 10
# Size of the gap that separates windows.
bspc config window_gap                   15

# Padding space added at the sides of the monitor or desktop.
bspc config top_padding                  40
bspc config bottom_padding               0

bspc config split_ratio                  0.62
bspc config borderless_monocle           true
bspc config gapless_monocle              true

# change focus window border color
{ echo; bspc subscribe node_focus; } |
     while read -r _; do
        sleep 0.05
        chwb -c CC6464 $(pfw)
     done
