#!/bin/bash

# ##############################################################################
# #                                  Config
# ##############################################################################

WALLPAPER_PATH="$HOME/Pictures/Wallpapers/wallpaper.jpg"

# ##############################################################################
# #                                  ENV VARS                                  #
# ##############################################################################

export BROWSER=firefox-nightly
export MONITOR=$(xrandr -q | grep primary | cut -d' ' -f1)
export MONITORS=( $(xrandr -q | grep ' connected' | cut -d' ' -f1) )
export QT_STYLE_OVERRIDE=kvantum

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

# start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
# no capslock, switch to ctrl
setxkbmap -option ctrl:nocaps
# turn off bell
xset -b
# start dunst
if pgrep -x dunst > /dev/null
then
    kill $(pidof dunst)
fi
dunst --startup_notification true --config $HOME/.config/dunst/dunstrc &
# start picom, it will autoreload config file, so it don't need to stop
picom --experimental-backends --config $HOME/.config/picom/picom.conf &
# start polybar
sh $HOME/.config/polybar/launch.sh
# start fcitx
fcitx5-remote -r
# auto lock screen
xautolock -time 10 -locker 'lock' -corners ---- -cornersize 30 &
# set wallpaper
hsetroot -fill $WALLPAPER_PATH
# battery checker
sh $HOME/.local/bin/check-battery.sh &
# start conky
sh $HOME/.config/conky/start.sh &
# start redshift
if pgrep -x redshift > /dev/null
then
    pid=$(pidof redshift)
    kill $pid
    # we need to wait redshift shutdown, otherwise color temperature is wrong.
    while kill -0 $pid 2>/dev/null; do sleep 0.01; done
fi
redshift &
latte-dock &

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

bspc rule -a FirefoxNightly                 desktop=^1 state=fullscreen
bspc rule -a Code                           desktop=^5 state=fullscreen
bspc rule -a TelegramDesktop                desktop=^7 state=tiled
bspc rule -a latte-dock                     sticky=on manage=off

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

MONITOR=${MONITOR:-${MONITORS[0]}}
bspc monitor $MONITOR -d I II III IV V VI VII

# pointer_modifier
#     Keyboard modifier used for moving or resizing windows. Accept the following values: shift, control, lock, mod1, mod2,
#     mod3, mod4, mod5.
bspc config pointer_modifier             Mod4  # Super(Win)

# window border width
bspc config border_width                 10
# Size of the gap that separates windows.
bspc config window_gap                   15

# Padding space added at the sides of the monitor or desktop.
bspc config top_padding                  40
bspc config bottom_padding               0

bspc config split_ratio                  0.62
bspc config borderless_monocle           true
bspc config gapless_monocle              true

# change focus window border color
{ echo; bspc subscribe node_focus; } |
     while read -r _; do
        sleep 0.05
        chwb -c CC6464 $(pfw)
     done
